name: retrouve_tout
description: Une application pour retrouver les objets perdus.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.0.0
  geolocator: ^9.0.0
  firebase_storage: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
